-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

-- Create the users_login table if it does not exist
CREATE TABLE IF NOT EXISTS public.users_login
(
    -- Primary key for the users_login table, auto-generated using a sequence
    user_id integer NOT NULL DEFAULT nextval('users_login_user_id_seq'::regclass),
    email_address character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_login_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_login_email_address_key UNIQUE (email_address)
);

END;
